#!/usr/bin/env python3
'''
Tiny Time Tracking tool

@author:    David Pochet <david.pochet@gmail.com>
@license:   https://www.mozilla.org/en-US/MPL/2.0/
'''

if __name__ == '__main__':
    print("Hello!")
